version: "3"

networks:
    frontend:
    backend:

services:
    httpd:
	image: 'httpd'
	networks:
	    - frontend
	    - backend

    mariadb:
	image: 'mariadb'
	networks:
	    - backend


     php:
	image: 'php-fpm'
	networks:
	    - backend
